//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBlog.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoBlog.Tests.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create session.
        /// </summary>
        internal static string ErrorCreateSession {
            get {
                return ResourceManager.GetString("ErrorCreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error returned.
        /// </summary>
        internal static string ErrorReturned {
            get {
                return ResourceManager.GetString("ErrorReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id returned instead of error.
        /// </summary>
        internal static string IdReturnedInsteadOfError {
            get {
                return ResourceManager.GetString("IdReturnedInsteadOfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test parameter present {0}.
        /// </summary>
        internal static string NoTestParameterPresent {
            get {
                return ResourceManager.GetString("NoTestParameterPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success returned instead of error.
        /// </summary>
        internal static string SuccessReturned {
            get {
                return ResourceManager.GetString("SuccessReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong comment list.
        /// </summary>
        internal static string WrongCommentList {
            get {
                return ResourceManager.GetString("WrongCommentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong post.
        /// </summary>
        internal static string WrongPost {
            get {
                return ResourceManager.GetString("WrongPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong post list.
        /// </summary>
        internal static string WrongPostList {
            get {
                return ResourceManager.GetString("WrongPostList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong comment amount in test data.
        /// </summary>
        internal static string WrongTestDataCommentAmount {
            get {
                return ResourceManager.GetString("WrongTestDataCommentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong post amount in test data.
        /// </summary>
        internal static string WrongTestDataPostAmount {
            get {
                return ResourceManager.GetString("WrongTestDataPostAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user amount in test data.
        /// </summary>
        internal static string WrongTestDataUserAmount {
            get {
                return ResourceManager.GetString("WrongTestDataUserAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong vote amount in test data.
        /// </summary>
        internal static string WrongTestDataVoteAmount {
            get {
                return ResourceManager.GetString("WrongTestDataVoteAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user.
        /// </summary>
        internal static string WrongUser {
            get {
                return ResourceManager.GetString("WrongUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user list.
        /// </summary>
        internal static string WrongUserList {
            get {
                return ResourceManager.GetString("WrongUserList", resourceCulture);
            }
        }
    }
}
