version: '3.5'

services:
  proxy:
    image: olmaad/demoblogfrontend
    container_name: "demoblognginx8080"
    ports:
    - "8080:80"
    networks:  
    - demoblognetwork

  backend:
    container_name: "demoblogbackend80"
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
    - demoblognetwork

networks:
  demoblognetwork:
    name: demoblognetwork
    driver: bridge 