name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    #run: docker login -u ${{ secrets.DockerhubLogin }} -p ${{ secrets.DockerhubPassword }} docker.io
    
    steps:
    - uses: actions/checkout@v1
    - name: Build blog
      run: docker-compose build
      working-directory: ./Docker/Build/Blog
    - name: Build tests
      run: docker-compose build
      working-directory: ./Docker/Build/Tests
    - name: Run blog
      run: |
        docker-compose build
        docker-compose up -d
      working-directory: ./Docker/Run/Blog
    - name: Run tests
      run: docker-compose up --exit-code-from tests
      working-directory: ./Docker/Run/Tests
    - name: Stop blog
      run: docker-compose down
      working-directory: ./Docker/Run/Blog
      
    #- name: Push blog docker
      #run: docker-compose push
      #working-directory: ./Docker/Build/Blog
